
all:
	make -C pb
	@echo
	@echo "Starting server. You can then try:"
	@echo "  go run client.go register Joe Sixpack     # to register a person"
	@echo "  go run client.go list                     # to list known persons"
	go run server.go
